import { supabase } from '../lib/supabase';

const ROLE_LABELS = {
  admin: 'Admin', project_manager: 'Project Manager', coordinator: 'Coordinator', inspector: 'Inspector', contractor_admin: 'Contractor Admin', contractor_user: 'Contractor', viewer: 'Read-only Viewer',
};
const STATUS_LABELS = {
  draft: 'Draft', submitted: 'Submitted', coordinator_review: 'Coordinator Review', ready_for_inspection: 'Ready for Inspection', inspector_review: 'Inspector Review', needs_rework: 'Needs Rework', revision_submitted: 'Revision Submitted', approved: 'Approved', closed: 'Closed',
};
const ISSUE_STATUS_LABELS = { open:'Open', in_progress:'In Progress', contractor_responded:'Contractor Responded', ready_for_review:'Ready for Review', resolved:'Resolved', closed:'Closed' };
export const roleLabel=(v)=>ROLE_LABELS[v]||v||'Viewer';
export const statusLabel=(v)=>STATUS_LABELS[v]||v||'Draft';
export const issueStatusLabel=(v)=>ISSUE_STATUS_LABELS[v]||v||'Open';
export const statusValue=(label)=>Object.entries(STATUS_LABELS).find(([,v])=>v===label)?.[0]||label;
export const issueStatusValue=(label)=>Object.entries(ISSUE_STATUS_LABELS).find(([,v])=>v===label)?.[0]||label;

export async function getOrganization(id){const {data,error}=await supabase.from('organizations').select('*').eq('id',id).single();if(error)throw error;return data}
export async function getProfiles(organizationId){const {data,error}=await supabase.from('profiles').select('id,full_name,email,role,active,contractor_company_id,created_at').eq('organization_id',organizationId).order('full_name');if(error)throw error;return data||[]}
export async function getContractors(organizationId){const {data,error}=await supabase.from('contractor_companies').select('*').eq('organization_id',organizationId).order('name');if(error)throw error;return data||[]}
export async function getProjects(){const {data,error}=await supabase.from('projects').select(`*,contractor_company:contractor_companies(id,name),coordinator:profiles!projects_coordinator_id_fkey(id,full_name),inspector:profiles!projects_inspector_id_fkey(id,full_name),issues(id,issue_number,title,description,sheet,priority,status,assigned_to,due_date,created_at,updated_at,pin_x,pin_y),files(id,file_name,mime_type,size_bytes,category,caption,revision_number,created_at,storage_path),revisions(id,version,label,status,created_at,file_id),project_checklist_items(id,label,sort_order,completed_at,completed_by),activity_events(id,event_type,description,created_at,actor_id)`).eq('archived',false).order('updated_at',{ascending:false});if(error)throw error;return data||[]}
export async function getIssueComments(issueId){const {data,error}=await supabase.from('issue_comments').select('id,body,created_at,author:profiles!issue_comments_author_id_fkey(id,full_name,role)').eq('issue_id',issueId).order('created_at');if(error)throw error;return data||[]}
export async function createProject(profile,values){const {data,error}=await supabase.from('projects').insert({organization_id:profile.organizationId,contractor_company_id:values.contractorCompanyId||null,project_number:values.projectNumber,name:values.name,description:values.description||'',coordinator_id:values.coordinatorId||null,inspector_id:values.inspectorId||null,status:'draft',due_date:values.dueDate||null,progress:5,created_by:profile.id}).select().single();if(error)throw error;await Promise.all([supabase.from('activity_events').insert({organization_id:profile.organizationId,project_id:data.id,actor_id:profile.id,event_type:'project_created',description:`${profile.name} created the project`}),supabase.from('project_checklist_items').insert(['As-built PDF uploaded','Required field photos uploaded','Fiber counts and stationing verified','All open issues resolved','Final package approved'].map((label,sort_order)=>({organization_id:profile.organizationId,project_id:data.id,label,sort_order}))) ]);return data}
export async function updateProject(projectId,changes,profile,description){const {error}=await supabase.from('projects').update(changes).eq('id',projectId);if(error)throw error;if(description)await supabase.from('activity_events').insert({organization_id:profile.organizationId,project_id:projectId,actor_id:profile.id,event_type:'project_updated',description})}
export async function createIssue(project,profile,values){const nextNumber=Math.max(0,...(project.issues||[]).map(i=>i.issue_number||0))+1;const {data,error}=await supabase.from('issues').insert({organization_id:profile.organizationId,project_id:project.id,issue_number:nextNumber,title:values.title,description:values.description||'',sheet:values.sheet||null,priority:values.priority||'medium',status:'open',assigned_to:values.assignedTo||null,due_date:values.dueDate||null,pin_x:Number(values.pinX||50),pin_y:Number(values.pinY||50),created_by:profile.id}).select().single();if(error)throw error;await supabase.from('activity_events').insert({organization_id:profile.organizationId,project_id:project.id,actor_id:profile.id,event_type:'issue_created',description:`${profile.name} created issue #${nextNumber}: ${values.title}`});return data}
export async function updateIssue(issueId,projectId,profile,changes,description){const {error}=await supabase.from('issues').update(changes).eq('id',issueId);if(error)throw error;if(description)await supabase.from('activity_events').insert({organization_id:profile.organizationId,project_id:projectId,actor_id:profile.id,event_type:'issue_updated',description})}
export async function addIssueComment(issueId,projectId,profile,body){const {error}=await supabase.from('issue_comments').insert({organization_id:profile.organizationId,issue_id:issueId,author_id:profile.id,body});if(error)throw error;await supabase.from('activity_events').insert({organization_id:profile.organizationId,project_id:projectId,actor_id:profile.id,event_type:'issue_comment',description:`${profile.name} commented on an issue`})}
const clean=(name)=>name.replace(/[^a-zA-Z0-9._-]/g,'-');
export async function uploadProjectFiles(project,profile,fileList,category,onProgress){const results=[];const files=Array.from(fileList||[]);for(let index=0;index<files.length;index+=1){const file=files[index];const path=`${profile.organizationId}/${project.id}/${crypto.randomUUID()}-${clean(file.name)}`;const {error:uploadError}=await supabase.storage.from('project-files').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(uploadError)throw uploadError;const {data,error}=await supabase.from('files').insert({organization_id:profile.organizationId,project_id:project.id,storage_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,category,uploaded_by:profile.id}).select().single();if(error)throw error;results.push(data);onProgress?.(Math.round(((index+1)/files.length)*100))}await supabase.from('activity_events').insert({organization_id:profile.organizationId,project_id:project.id,actor_id:profile.id,event_type:'files_uploaded',description:`${profile.name} uploaded ${files.length} ${category.toLowerCase()} file${files.length===1?'':'s'}`});return results}
export async function uploadRevision(project,profile,file,onProgress){const version=Math.max(0,...(project.revisions||[]).map(r=>r.version||0))+1;const [uploaded]=await uploadProjectFiles(project,profile,[file],`Revision ${version}`,onProgress);const {error}=await supabase.from('revisions').insert({organization_id:profile.organizationId,project_id:project.id,version,file_id:uploaded.id,label:file.name,status:'revision_submitted',uploaded_by:profile.id});if(error)throw error;await updateProject(project.id,{status:'revision_submitted',progress:Math.max(project.progress||0,75)},profile,`${profile.name} submitted revision ${version}`)}
export async function getSignedFileUrl(path){const {data,error}=await supabase.storage.from('project-files').createSignedUrl(path,300);if(error)throw error;return data.signedUrl}
export async function toggleChecklist(item,profile){const done=!item.completed_at;const {error}=await supabase.from('project_checklist_items').update({completed_at:done?new Date().toISOString():null,completed_by:done?profile.id:null}).eq('id',item.id);if(error)throw error}
export async function getNotifications(profileId){const {data,error}=await supabase.from('notifications').select('*').eq('recipient_id',profileId).order('created_at',{ascending:false}).limit(30);if(error)throw error;return data||[]}
export async function markNotificationsRead(profileId){const {error}=await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('recipient_id',profileId).is('read_at',null);if(error)throw error}
export async function updateProfile(profileId,changes){const {error}=await supabase.from('profiles').update(changes).eq('id',profileId);if(error)throw error}
export async function createContractor(organizationId,name){const {data,error}=await supabase.from('contractor_companies').insert({organization_id:organizationId,name}).select().single();if(error)throw error;return data}
export async function inviteUser(values){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Your session has expired. Sign in again.');const payload={...values,redirectTo:`${window.location.origin}/app/setup-password`};const {data,error}=await supabase.functions.invoke('invite-user',{body:payload,headers:{Authorization:`Bearer ${session.access_token}`}});if(error)throw error;if(!data?.success)throw new Error(data?.error||'Invitation failed.');return data}


export async function removeUser(profileId){
  const {data:{session}}=await supabase.auth.getSession();
  if(!session)throw new Error('Your session has expired. Sign in again.');
  const {data,error}=await supabase.functions.invoke('remove-user',{body:{userId:profileId},headers:{Authorization:`Bearer ${session.access_token}`}});
  if(error)throw error;
  if(!data?.success)throw new Error(data?.error||'User removal failed.');
  return data;
}
